overrides:
  devtools-protocol: 0.0.1681094
  hono: 4.13.1
  "@hono/node-server": 2.1.0
  fast-uri: 4.1.2
  protobufjs: 8.7.2
  vite: 8.2.1

allowBuilds:
  "@google/genai": false
  esbuild: true

minimumReleaseAge: 2880
